"""limites de plano para eventos e academia

Revision ID: 198617184918
Revises: cfecac34cf53
Create Date: 2026-08-16 17:44:18.073782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198617184918'
down_revision: Union[str, Sequence[str], None] = 'cfecac34cf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planos', sa.Column('max_locais', sa.Integer(), nullable=True))
    op.add_column('planos', sa.Column('max_sessoes_mes', sa.Integer(), nullable=True))
    op.add_column('planos', sa.Column('max_turmas', sa.Integer(), nullable=True))
    op.add_column('planos', sa.Column('max_matriculas_ativas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'max_matriculas_ativas')
    op.drop_column('planos', 'max_turmas')
    op.drop_column('planos', 'max_sessoes_mes')
    op.drop_column('planos', 'max_locais')
    # ### end Alembic commands ###
