"""cartao e boleto na fatura da assinatura

Revision ID: 2a1e59fc77da
Revises: a286a9e35813
Create Date: 2026-08-13 22:48:54.849502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1e59fc77da'
down_revision: Union[str, Sequence[str], None] = 'a286a9e35813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faturas_empresa', sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'CARTAO', 'PIX', 'BOLETO', 'OUTRO', name='formapagamento'), nullable=True))
    op.add_column('faturas_empresa', sa.Column('boleto_url', sa.String(length=300), nullable=True))
    op.add_column('faturas_empresa', sa.Column('boleto_codigo_barras', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faturas_empresa', 'boleto_codigo_barras')
    op.drop_column('faturas_empresa', 'boleto_url')
    op.drop_column('faturas_empresa', 'forma_pagamento')
    # ### end Alembic commands ###
