"""adiciona checklist pre-viagem do motorista

Revision ID: 3540b75a69ea
Revises: 9f3c97f852cc
Create Date: 2026-08-12 16:16:26.295263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3540b75a69ea'
down_revision: Union[str, Sequence[str], None] = '9f3c97f852cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists_viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('motorista_nome', sa.String(length=150), nullable=False),
    sa.Column('tipo_viagem', sa.Enum('VIAGEM', 'FRETAMENTO', 'FRETE', name='tipoviagemjornada'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('pneus_ok', sa.Boolean(), nullable=False),
    sa.Column('oleo_ok', sa.Boolean(), nullable=False),
    sa.Column('combustivel_ok', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklists_viagem')
    # ### end Alembic commands ###
