"""pedido de pagamento pix e cobranca de fatura pendente

Revision ID: 358b5a7c972b
Revises: 8f975c721862
Create Date: 2026-08-10 16:44:19.755889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358b5a7c972b'
down_revision: Union[str, Sequence[str], None] = '8f975c721862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('poltrona_viagem_id', sa.Integer(), nullable=False),
    sa.Column('parada_origem_id', sa.Integer(), nullable=False),
    sa.Column('parada_destino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=150), nullable=False),
    sa.Column('cliente_documento', sa.String(length=30), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'CARTAO', 'PIX', 'OUTRO', name='formapagamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pix_copia_cola', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'EXPIRADO', 'CANCELADO', name='statuspedidopagamento'), nullable=False),
    sa.Column('passagem_id', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parada_destino_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['parada_origem_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagens.id'], ),
    sa.ForeignKeyConstraint(['poltrona_viagem_id'], ['poltronas_viagem.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('faturas_empresa', sa.Column('pix_copia_cola', sa.String(length=300), nullable=True))
    op.add_column('faturas_empresa', sa.Column('pix_expira_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faturas_empresa', 'pix_expira_em')
    op.drop_column('faturas_empresa', 'pix_copia_cola')
    op.drop_table('pedidos_pagamento')
    # ### end Alembic commands ###
