"""soft delete de empresa

Revision ID: 3f8388b6bbe7
Revises: 198617184918
Create Date: 2026-08-17 14:12:34.050302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8388b6bbe7'
down_revision: Union[str, Sequence[str], None] = '198617184918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('excluida_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'excluida_em')
    # ### end Alembic commands ###
