"""avaliacoes pos viagem e pos fretamento

Revision ID: 43b9a2077bee
Revises: 358b5a7c972b
Create Date: 2026-08-10 17:06:34.102497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b9a2077bee'
down_revision: Union[str, Sequence[str], None] = '358b5a7c972b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('passagem_id', sa.Integer(), nullable=True),
    sa.Column('fretamento_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(passagem_id IS NOT NULL AND fretamento_id IS NULL) OR (passagem_id IS NULL AND fretamento_id IS NOT NULL)', name='ck_avaliacao_um_alvo'),
    sa.ForeignKeyConstraint(['fretamento_id'], ['fretamentos.id'], ),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagens.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fretamento_id'),
    sa.UniqueConstraint('passagem_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
