"""adiciona telefone de contato e texto da loja em empresas

Revision ID: 5096051802f6
Revises: ac66b62690c7
Create Date: 2026-08-11 15:48:15.511831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5096051802f6'
down_revision: Union[str, Sequence[str], None] = 'ac66b62690c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('telefone_contato', sa.String(length=30), nullable=True))
    op.add_column('empresas', sa.Column('texto_loja', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'texto_loja')
    op.drop_column('empresas', 'telefone_contato')
    # ### end Alembic commands ###
