"""modulos habilitaveis fretamento e passagens por plano e empresa

Revision ID: 5ec945baf311
Revises: 5baaf7bb8401
Create Date: 2026-08-10 21:17:11.035090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec945baf311'
down_revision: Union[str, Sequence[str], None] = '5baaf7bb8401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('empresas', sa.Column('fretamento_ativo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('empresas', sa.Column('passagens_ativo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('planos', sa.Column('modulo_fretamento', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('planos', sa.Column('modulo_passagens', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'modulo_passagens')
    op.drop_column('planos', 'modulo_fretamento')
    op.drop_column('empresas', 'passagens_ativo')
    op.drop_column('empresas', 'fretamento_ativo')
    # ### end Alembic commands ###
