"""adiciona repasse de comissao para parceiros

Revision ID: 66dfa0319f90
Revises: 5096051802f6
Create Date: 2026-08-11 16:24:27.198299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dfa0319f90'
down_revision: Union[str, Sequence[str], None] = '5096051802f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repasses_parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=False),
    sa.Column('periodo_fim', sa.DateTime(), nullable=False),
    sa.Column('total_passagens', sa.Integer(), nullable=False),
    sa.Column('valor_passagens', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fretes', sa.Integer(), nullable=False),
    sa.Column('valor_fretes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', name='statusrepasse'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repasses_parceiro')
    # ### end Alembic commands ###
