"""adiciona isencao de cobranca por empresa

Revision ID: 75a7c934e0be
Revises: 7b06526b9442
Create Date: 2026-08-13 15:44:30.229823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a7c934e0be'
down_revision: Union[str, Sequence[str], None] = '7b06526b9442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('isento_cobranca', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'isento_cobranca')
    # ### end Alembic commands ###
