"""baseline schema

Revision ID: 7bbf21900acb
Revises: 
Create Date: 2026-08-03 17:48:56.731595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbf21900acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('email_contato', sa.String(length=150), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('onibus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('identificacao', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('CONVENCIONAL', 'EXECUTIVO', 'LEITO', name='tipoonibus'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN_EMPRESA', 'FUNCIONARIO', 'CLIENTE', name='userrole'), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('poltronas_onibus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onibus_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('andar', sa.Integer(), nullable=False),
    sa.Column('fileira', sa.Integer(), nullable=False),
    sa.Column('coluna', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['onibus_id'], ['onibus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('onibus_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_partida', sa.DateTime(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['onibus_id'], ['onibus.id'], ),
    sa.ForeignKeyConstraint(['rota_id'], ['rotas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poltronas_viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('poltrona_onibus_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LIVRE', 'HOLD', 'BLOQUEADA', 'VENDIDA', name='statuspoltrona'), nullable=False),
    sa.Column('hold_expira_em', sa.DateTime(), nullable=True),
    sa.Column('hold_usuario_id', sa.Integer(), nullable=True),
    sa.Column('bloqueio_motivo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['hold_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['poltrona_onibus_id'], ['poltronas_onibus.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('poltrona_viagem_id', sa.Integer(), nullable=False),
    sa.Column('cliente_usuario_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=150), nullable=False),
    sa.Column('cliente_documento', sa.String(length=30), nullable=False),
    sa.Column('vendido_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CANCELADA', name='statuspassagem'), nullable=False),
    sa.Column('localizador', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('checkin_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['poltrona_viagem_id'], ['poltronas_viagem.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['vendido_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localizador')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passagem_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'CARTAO', 'PIX', 'OUTRO', name='formapagamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passagem_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('passagens')
    op.drop_table('poltronas_viagem')
    op.drop_table('viagens')
    op.drop_table('poltronas_onibus')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('rotas')
    op.drop_table('onibus')
    op.drop_table('empresas')
    # ### end Alembic commands ###
