"""frete generico sem depender de onibus, icone customizavel no mapa

Revision ID: 810b3ae7c467
Revises: 5ec945baf311
Create Date: 2026-08-10 21:54:58.632334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810b3ae7c467'
down_revision: Union[str, Sequence[str], None] = '5ec945baf311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=12), nullable=False),
    sa.Column('remetente_nome', sa.String(length=150), nullable=False),
    sa.Column('remetente_contato', sa.String(length=100), nullable=True),
    sa.Column('destinatario_nome', sa.String(length=150), nullable=False),
    sa.Column('destinatario_contato', sa.String(length=100), nullable=True),
    sa.Column('descricao_carga', sa.String(length=200), nullable=True),
    sa.Column('origem', sa.String(length=150), nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=False),
    sa.Column('data_hora_coleta', sa.DateTime(), nullable=False),
    sa.Column('data_hora_entrega_prevista', sa.DateTime(), nullable=True),
    sa.Column('motorista_nome', sa.String(length=150), nullable=True),
    sa.Column('veiculo_descricao', sa.String(length=150), nullable=True),
    sa.Column('distancia_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor_por_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADO', 'CONFIRMADO', 'EM_TRANSITO', 'ENTREGUE', 'CANCELADO', name='statusfrete'), nullable=False),
    sa.Column('icone_mapa', sa.String(length=8), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_rastreio')
    )
    op.create_table('posicoes_frete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frete_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['frete_id'], ['fretes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('empresas', sa.Column('frete_ativo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('fretamentos', sa.Column('icone_mapa', sa.String(length=8), nullable=False, server_default='🚌'))
    op.add_column('planos', sa.Column('modulo_frete', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'modulo_frete')
    op.drop_column('fretamentos', 'icone_mapa')
    op.drop_column('empresas', 'frete_ativo')
    op.drop_table('posicoes_frete')
    op.drop_table('fretes')
    # ### end Alembic commands ###
