"""add reembolso fields and poltrona categoria

Revision ID: 8eed861ef93f
Revises: e8541f13fe97
Create Date: 2026-08-03 19:51:46.110405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eed861ef93f'
down_revision: Union[str, Sequence[str], None] = 'e8541f13fe97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('valor_reembolsado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pagamentos', sa.Column('motivo_reembolso', sa.String(length=200), nullable=True))
    op.add_column('pagamentos', sa.Column('reembolsado_em', sa.DateTime(), nullable=True))
    op.add_column('poltronas_onibus', sa.Column('categoria', sa.String(length=30), nullable=False, server_default='padrao'))
    op.add_column('poltronas_onibus', sa.Column('multiplicador_preco', sa.Numeric(precision=4, scale=2), nullable=False, server_default='1.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poltronas_onibus', 'multiplicador_preco')
    op.drop_column('poltronas_onibus', 'categoria')
    op.drop_column('pagamentos', 'reembolsado_em')
    op.drop_column('pagamentos', 'motivo_reembolso')
    op.drop_column('pagamentos', 'valor_reembolsado')
    # ### end Alembic commands ###
