"""fretamento e rastreamento gps

Revision ID: 8f975c721862
Revises: c276618b86e4
Create Date: 2026-08-10 12:40:48.207285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f975c721862'
down_revision: Union[str, Sequence[str], None] = 'c276618b86e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fretamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=12), nullable=False),
    sa.Column('cliente_nome', sa.String(length=150), nullable=False),
    sa.Column('cliente_documento', sa.String(length=30), nullable=True),
    sa.Column('cliente_contato', sa.String(length=100), nullable=True),
    sa.Column('origem', sa.String(length=150), nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=False),
    sa.Column('data_hora_saida', sa.DateTime(), nullable=False),
    sa.Column('data_hora_retorno_prevista', sa.DateTime(), nullable=True),
    sa.Column('onibus_id', sa.Integer(), nullable=True),
    sa.Column('motorista_nome', sa.String(length=150), nullable=True),
    sa.Column('distancia_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor_por_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ORCAMENTO', 'CONFIRMADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO', name='statusfretamento'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['onibus_id'], ['onibus.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_rastreio')
    )
    op.create_table('posicoes_fretamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fretamento_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fretamento_id'], ['fretamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('empresas', sa.Column('preco_km_fretamento', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'preco_km_fretamento')
    op.drop_table('posicoes_fretamento')
    op.drop_table('fretamentos')
    # ### end Alembic commands ###
