"""adiciona manutencao de frota: documentos com vencimento e quilometragem

Revision ID: 95c3a0ecf08d
Revises: 66dfa0319f90
Create Date: 2026-08-11 16:45:32.872879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c3a0ecf08d'
down_revision: Union[str, Sequence[str], None] = '66dfa0319f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_onibus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('onibus_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CRLV', 'SEGURO', 'REVISAO', 'OUTRO', name='tipodocumentoonibus'), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['onibus_id'], ['onibus.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('onibus', sa.Column('quilometragem_atual', sa.Numeric(precision=10, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onibus', 'quilometragem_atual')
    op.drop_table('documentos_onibus')
    # ### end Alembic commands ###
