"""adiciona credenciais mercadopago por empresa

Revision ID: 9f3c97f852cc
Revises: 3bc04a841afc
Create Date: 2026-08-12 16:07:54.774662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3c97f852cc'
down_revision: Union[str, Sequence[str], None] = '3bc04a841afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('mercadopago_access_token', sa.String(length=200), nullable=True))
    op.add_column('empresas', sa.Column('mercadopago_public_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'mercadopago_public_key')
    op.drop_column('empresas', 'mercadopago_access_token')
    # ### end Alembic commands ###
