"""adiciona programa de indicacao

Revision ID: a286a9e35813
Revises: bda744d8542a
Create Date: 2026-08-13 17:29:53.129158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a286a9e35813'
down_revision: Union[str, Sequence[str], None] = 'bda744d8542a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('indicacao_ativa', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('empresas', sa.Column('indicacao_desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=True))
    with op.batch_alter_table('usuarios') as batch:
        batch.add_column(sa.Column('codigo_indicacao', sa.String(length=12), nullable=True))
        batch.add_column(sa.Column('indicado_por_usuario_id', sa.Integer(), nullable=True))
        batch.create_unique_constraint('uq_usuarios_codigo_indicacao', ['codigo_indicacao'])
        batch.create_foreign_key('fk_usuarios_indicado_por_usuario_id', 'usuarios', ['indicado_por_usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios') as batch:
        batch.drop_constraint('fk_usuarios_indicado_por_usuario_id', type_='foreignkey')
        batch.drop_constraint('uq_usuarios_codigo_indicacao', type_='unique')
        batch.drop_column('indicado_por_usuario_id')
        batch.drop_column('codigo_indicacao')
    op.drop_column('empresas', 'indicacao_desconto_percentual')
    op.drop_column('empresas', 'indicacao_ativa')
    # ### end Alembic commands ###
