"""adiciona gateway_ref em pedido_pagamento e taxa de transacao na plataforma

Revision ID: b8e6085594ef
Revises: f0c05d8ea00e
Create Date: 2026-08-13 09:06:02.807313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e6085594ef'
down_revision: Union[str, Sequence[str], None] = 'f0c05d8ea00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracao_plataforma', sa.Column('taxa_transacao_percentual', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pedidos_pagamento', sa.Column('gateway_ref', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos_pagamento', 'gateway_ref')
    op.drop_column('configuracao_plataforma', 'taxa_transacao_percentual')
    # ### end Alembic commands ###
