"""adiciona escala de motorista e motorista_nome em viagens

Revision ID: bca9dd9cbe8c
Revises: 95c3a0ecf08d
Create Date: 2026-08-11 17:03:29.666284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca9dd9cbe8c'
down_revision: Union[str, Sequence[str], None] = '95c3a0ecf08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jornadas_motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('motorista_nome', sa.String(length=150), nullable=False),
    sa.Column('tipo_viagem', sa.Enum('VIAGEM', 'FRETAMENTO', 'FRETE', name='tipoviagemjornada'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('viagens', sa.Column('motorista_nome', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viagens', 'motorista_nome')
    op.drop_table('jornadas_motorista')
    # ### end Alembic commands ###
