"""adiciona rastreamento ao vivo para viagem

Revision ID: bda744d8542a
Revises: bffc760d94a2
Create Date: 2026-08-13 17:15:27.375117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda744d8542a'
down_revision: Union[str, Sequence[str], None] = 'bffc760d94a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posicoes_viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viagens') as batch:
        batch.add_column(sa.Column('codigo_rastreio', sa.String(length=12), nullable=True))
        batch.create_unique_constraint('uq_viagens_codigo_rastreio', ['codigo_rastreio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagens') as batch:
        batch.drop_constraint('uq_viagens_codigo_rastreio', type_='unique')
        batch.drop_column('codigo_rastreio')
    op.drop_table('posicoes_viagem')
    # ### end Alembic commands ###
