"""trava modulos premium do plano completo

Revision ID: bffc760d94a2
Revises: 75a7c934e0be
Create Date: 2026-08-13 16:32:38.366777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffc760d94a2'
down_revision: Union[str, Sequence[str], None] = '75a7c934e0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planos', sa.Column('modulo_frota', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('planos', sa.Column('modulo_motorista', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('planos', sa.Column('modulo_dre', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('planos', sa.Column('modulo_white_label', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('planos', sa.Column('modulo_nfse', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###

    # Trava os diferenciais do plano Completo pros planos que não devem
    # incluí-los, por nome (não por id, pra funcionar igual em qualquer
    # banco). Basico (legado) e Completo continuam com tudo liberado —
    # o server_default acima já cobre isso.
    op.execute(
        """
        UPDATE planos
        SET modulo_frota = 0, modulo_motorista = 0, modulo_dre = 0,
            modulo_white_label = 0, modulo_nfse = 0
        WHERE nome IN ('Essencial', 'Profissional', 'Logistica')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'modulo_nfse')
    op.drop_column('planos', 'modulo_white_label')
    op.drop_column('planos', 'modulo_dre')
    op.drop_column('planos', 'modulo_motorista')
    op.drop_column('planos', 'modulo_frota')
    # ### end Alembic commands ###
