"""planos, faturas e assinatura da empresa

Revision ID: c276618b86e4
Revises: b4bb41b26516
Create Date: 2026-08-06 09:09:51.452073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c276618b86e4'
down_revision: Union[str, Sequence[str], None] = 'b4bb41b26516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_onibus', sa.Integer(), nullable=True),
    sa.Column('max_funcionarios', sa.Integer(), nullable=True),
    sa.Column('max_viagens_mes', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faturas_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'FALHOU', 'CANCELADA', name='statusfatura'), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas') as batch_op:
        batch_op.add_column(sa.Column('plano_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'status_assinatura',
                sa.Enum('TRIAL', 'ATIVA', 'INADIMPLENTE', 'SUSPENSA', 'CANCELADA', name='statusassinatura'),
                nullable=False,
                server_default='TRIAL',
            )
        )
        batch_op.create_foreign_key('fk_empresas_plano', 'planos', ['plano_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas') as batch_op:
        batch_op.drop_constraint('fk_empresas_plano', type_='foreignkey')
        batch_op.drop_column('status_assinatura')
        batch_op.drop_column('plano_id')
    op.drop_table('faturas_empresa')
    op.drop_table('planos')
    # ### end Alembic commands ###
