"""academias e estudios com vaga limitada

Revision ID: cfecac34cf53
Revises: 1e8adb553414
Create Date: 2026-08-14 22:10:37.141804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfecac34cf53'
down_revision: Union[str, Sequence[str], None] = '1e8adb553414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('capacidade_vagas', sa.Integer(), nullable=False),
    sa.Column('instrutor', sa.String(length=150), nullable=True),
    sa.Column('preco_avulso', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias_turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('capacidade_vagas', sa.Integer(), nullable=False),
    sa.Column('cancelada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cliente_usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MENSAL_ILIMITADO', 'PACOTE_AULAS', name='tipomatricula'), nullable=False),
    sa.Column('valor_mensalidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aulas_por_ciclo', sa.Integer(), nullable=True),
    sa.Column('aulas_utilizadas_ciclo_atual', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'ATIVA', 'INADIMPLENTE', 'SUSPENSA', 'CANCELADA', name='statusmatricula'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('cancelada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faturas_matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('cliente_usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'FALHOU', 'CANCELADA', name='statusfatura'), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'CARTAO', 'PIX', 'BOLETO', 'OUTRO', name='formapagamento'), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('pix_copia_cola', sa.String(length=300), nullable=True),
    sa.Column('pix_expira_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ocorrencia_turma_id', sa.Integer(), nullable=False),
    sa.Column('cliente_usuario_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=150), nullable=True),
    sa.Column('cliente_documento', sa.String(length=30), nullable=True),
    sa.Column('matricula_id', sa.Integer(), nullable=True),
    sa.Column('tipo_reserva', sa.Enum('MATRICULA', 'AVULSA', name='tiporeserva'), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CANCELADA', name='statuspassagem'), nullable=False),
    sa.Column('preco_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'CARTAO', 'PIX', 'BOLETO', 'OUTRO', name='formapagamento'), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('checkin_em', sa.DateTime(), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.ForeignKeyConstraint(['ocorrencia_turma_id'], ['ocorrencias_turma.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.add_column('empresas', sa.Column('academia_ativo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('empresas', sa.Column('preco_padrao_mensalidade_academia', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('planos', sa.Column('modulo_academia', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'modulo_academia')
    op.drop_column('empresas', 'preco_padrao_mensalidade_academia')
    op.drop_column('empresas', 'academia_ativo')
    op.drop_table('reservas_aula')
    op.drop_table('faturas_matricula')
    op.drop_table('matriculas')
    op.drop_table('ocorrencias_turma')
    op.drop_table('turmas')
    # ### end Alembic commands ###
