"""interline entre empresas

Revision ID: e200cfe8adcf
Revises: 2a1e59fc77da
Create Date: 2026-08-14 14:45:03.659231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e200cfe8adcf'
down_revision: Union[str, Sequence[str], None] = '2a1e59fc77da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conexoes_interline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rota_perna_a_id', sa.Integer(), nullable=False),
    sa.Column('rota_perna_b_id', sa.Integer(), nullable=False),
    sa.Column('empresa_a_id', sa.Integer(), nullable=False),
    sa.Column('empresa_b_id', sa.Integer(), nullable=False),
    sa.Column('parada_conexao_nome', sa.String(length=100), nullable=False),
    sa.Column('minutos_conexao_minima', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_a_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['empresa_b_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['rota_perna_a_id'], ['rotas.id'], ),
    sa.ForeignKeyConstraint(['rota_perna_b_id'], ['rotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_interline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conexao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=150), nullable=False),
    sa.Column('cliente_documento', sa.String(length=30), nullable=False),
    sa.Column('cliente_telefone', sa.String(length=30), nullable=True),
    sa.Column('tipo_documento', sa.Enum('CPF', 'RG', 'CNH', 'PASSAPORTE', 'OUTRO', name='tipodocumento'), nullable=False),
    sa.Column('categoria_passageiro', sa.Enum('COMUM', 'IDOSO', 'PCD', 'CRIANCA_COLO', name='categoriapassageiro'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'CARTAO', 'PIX', 'BOLETO', 'OUTRO', name='formapagamento'), nullable=False),
    sa.Column('viagem_perna_a_id', sa.Integer(), nullable=False),
    sa.Column('poltrona_perna_a_id', sa.Integer(), nullable=False),
    sa.Column('parada_origem_a_id', sa.Integer(), nullable=False),
    sa.Column('parada_destino_a_id', sa.Integer(), nullable=False),
    sa.Column('viagem_perna_b_id', sa.Integer(), nullable=False),
    sa.Column('poltrona_perna_b_id', sa.Integer(), nullable=False),
    sa.Column('parada_origem_b_id', sa.Integer(), nullable=False),
    sa.Column('parada_destino_b_id', sa.Integer(), nullable=False),
    sa.Column('passagem_perna_a_id', sa.Integer(), nullable=True),
    sa.Column('passagem_perna_b_id', sa.Integer(), nullable=True),
    sa.Column('valor_perna_a', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_perna_b', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_PAGAMENTO', 'CONFIRMADO', 'CANCELADO', name='statuspedidointerline'), nullable=False),
    sa.Column('pix_copia_cola', sa.String(length=300), nullable=True),
    sa.Column('pix_expira_em', sa.DateTime(), nullable=True),
    sa.Column('gateway_ref', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conexao_id'], ['conexoes_interline.id'], ),
    sa.ForeignKeyConstraint(['parada_destino_a_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['parada_destino_b_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['parada_origem_a_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['parada_origem_b_id'], ['paradas.id'], ),
    sa.ForeignKeyConstraint(['passagem_perna_a_id'], ['passagens.id'], ),
    sa.ForeignKeyConstraint(['passagem_perna_b_id'], ['passagens.id'], ),
    sa.ForeignKeyConstraint(['poltrona_perna_a_id'], ['poltronas_viagem.id'], ),
    sa.ForeignKeyConstraint(['poltrona_perna_b_id'], ['poltronas_viagem.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viagem_perna_a_id'], ['viagens.id'], ),
    sa.ForeignKeyConstraint(['viagem_perna_b_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acertos_interline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_interline_id', sa.Integer(), nullable=False),
    sa.Column('empresa_devedora_id', sa.Integer(), nullable=False),
    sa.Column('empresa_credora_id', sa.Integer(), nullable=False),
    sa.Column('valor_devido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', name='statusrepasse'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_credora_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['empresa_devedora_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['pedido_interline_id'], ['pedidos_interline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acertos_interline')
    op.drop_table('pedidos_interline')
    op.drop_table('conexoes_interline')
    # ### end Alembic commands ###
