"""cupom de desconto

Revision ID: eb2e1f9cf3e2
Revises: 07cddbafa6a0
Create Date: 2026-08-10 22:54:02.894126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2e1f9cf3e2'
down_revision: Union[str, Sequence[str], None] = '07cddbafa6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.Enum('PERCENTUAL', 'FIXO', name='tipocupom'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('valido_ate', sa.DateTime(), nullable=True),
    sa.Column('max_usos', sa.Integer(), nullable=True),
    sa.Column('usos_atuais', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('passagens', sa.Column('codigo_cupom', sa.String(length=30), nullable=True))
    op.add_column('pedidos_pagamento', sa.Column('codigo_cupom', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos_pagamento', 'codigo_cupom')
    op.drop_column('passagens', 'codigo_cupom')
    op.drop_table('cupons')
    # ### end Alembic commands ###
