"""adiciona configuracao de cobranca da plataforma

Revision ID: f0c05d8ea00e
Revises: af9b36746f3d
Create Date: 2026-08-12 18:04:11.893792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c05d8ea00e'
down_revision: Union[str, Sequence[str], None] = 'af9b36746f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_plataforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mercadopago_access_token', sa.String(length=200), nullable=True),
    sa.Column('mercadopago_public_key', sa.String(length=200), nullable=True),
    sa.Column('modo_cobranca', sa.Enum('AUTOMATICA', 'MANUAL', 'DESATIVADA', name='modocobranca'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_plataforma')
    # ### end Alembic commands ###
